dist: xenial
language: python
cache: pip
notifications:
  email: false
python:
    - '3.7'
    - '3.6'
    - '3.5'
    - '3.4'
install:
    - pip install -r dev-requirements.txt
script:
    - pytest
stages:
    - lint
    - test
    - deploy
jobs:
  include:
      - stage: lint
        install:
            - pip install black
        script:
            - black --check orthanc_rest_client tests
      - stage: deploy
        deploy:
            - provider: pypi
              user: teffalump
              password:
                secure: "q+9zWwWwHHj67YNtVrmiMmD0OJTRoa8ELc2CVvXTQVue+e5213W5NVz1ERdTp2iW7/bM51zumYsOVOedJLpEryerJASE+jyjTrQtJwJQrWCUdDnPbuxq5eK2sxQkr0wdeLeIn/8gY3HgkaMcQXlNMwvIDLCLcFP0SHaP5fCBMXCyPP1JpjEk0rJUkchOACa7CWdfVy1/RCFAFJ9CWH+W1QZHehAxAPRmlGvqqVQCdDV5YkSClWDvJnPzKygiKZsGz/H/YUgbT6q+T5mmXg4MFJaYhkq437R2bDZZ6jgoDGK8gAgFHS//XcZOCv/P1GZXj6Jrrfx2gHDqiZczGeybUW/LIAy5K/YOOqrXUJEqVLwuPGAkBr/GN9y/6a5H7VIyUiPLQNFZDNuvRRoNSJJzuxwUkX6OO/CaQg/al0/iZuFceuLDPLLnJJ3ee8BWzL79dQiI+D9c6qgWUDiXZ+Ht4NrL26xv0i/dv4pYHS7GWmggjS/siUOLllGtWP+pYjtqNvr79OHsWWYmft9vyze/guzWPcQJUSbl1nu3gj85BLGZzrFf6TG64DPPQf360QUaG44vuJHAeUqbM7q/C4ciBQ2pri6sceirjBvLBWAYBlX3kCEwXfvVxX/NmpKybVrfbU5GR8qqYEzUz9i/sITiTSie5cRQ3QR99/HXaXpQGJE="
              distributions: "sdist bdist_wheel"
              skip_cleanup: true
              skip_existing: true
              on:
                repo: teffalump/orthanc_rest_client
                branch: master
                tags: true
